# Generated by Django 3.2.13 on 2022-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
