# Generated by Django 3.2.13 on 2022-08-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20220803_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
