# Generated by Django 3.2.13 on 2022-08-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='alex', max_length=255, verbose_name='Url'),
        ),
    ]
