# Generated by Django 3.2.13 on 2022-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='abcdr', max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
