# Generated by Django 3.2.13 on 2022-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
