# Generated by Django 3.2.13 on 2022-08-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20220804_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isbn',
            field=models.CharField(max_length=50, verbose_name='ISBN'),
        ),
    ]
