# Generated by Django 3.2.13 on 2022-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_news_fb2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='year',
            field=models.CharField(blank=True, max_length=10, verbose_name='year'),
        ),
    ]
