# Generated by Django 3.2.13 on 2022-09-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_alter_news_idflib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='news',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='year'),
        ),
    ]
