# Generated by Django 3.2.13 on 2022-08-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
