# Generated by Django 3.2.13 on 2022-08-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='123', max_length=255, verbose_name='Url'),
        ),
    ]
