# Generated by Django 3.2.13 on 2022-08-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_category_id_flib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Серия')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('id_flib', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.series', verbose_name='Серия'),
        ),
    ]
