# Generated by Django 3.2.13 on 2022-08-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20220804_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='series_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(),
        ),
    ]
