# Generated by Django 3.2.13 on 2022-08-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_news_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='year',
            field=models.CharField(default='1000', max_length=10, verbose_name='year'),
        ),
    ]
