# Generated by Django 3.2.13 on 2022-08-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20220804_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='idflib',
            field=models.IntegerField(verbose_name='id flibusta'),
        ),
    ]
