# Generated by Django 3.2.13 on 2022-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_alter_news_idflib'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='fb2',
            field=models.FileField(blank=True, upload_to='books/%Y/%m/%d/', verbose_name='fb2 файл'),
        ),
    ]
